databases:
  - name: amciuday-db
    databaseName: amciuday
    user: amciuday
    plan: free

services:
  # Backend API Service
  - type: web
    name: amciuday-backend
    env: python
    buildCommand: "cd apps/backend && pip install -r requirements.txt"
    startCommand: "cd apps/backend && python start.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amciuday-db
          property: connectionString
      - key: PORT
        value: 8000
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health
    
  # Frontend Static Site
  - type: web
    name: amciuday-frontend
    env: static
    buildCommand: "cd apps/frontend && npm ci && npm run build"
    staticPublishPath: ./apps/frontend/dist
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
      - apps/frontend/src/**
      - apps/frontend/public/**
      - apps/frontend/index.html
      - apps/frontend/package.json
      - apps/frontend/package-lock.json
      - apps/frontend/vite.config.ts
      - apps/frontend/tsconfig.json
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: max-age=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html